apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.front.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.front.name }}
    app.kubernetes.io/part-of: helm-app
    app.kubernetes.io/version: {{ .Values.front.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.front.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.front.name }}
      app.kubernetes.io/part-of: helm-app
      app.kubernetes.io/version: {{ .Values.front.image.tag }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.front.name }}
        app.kubernetes.io/part-of: helm-app
        app.kubernetes.io/version: {{ .Values.front.image.tag }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Values.front.name }}
          image: {{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}
          imagePullPolicy: {{ .Values.front.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HELM_BACK_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: helm_back_api_url
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
